global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mama-bear-backend'
    static_configs:
      - targets: ['mama-bear-backend:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mama-bear-mcp'
    static_configs:
      - targets: ['mama-bear-mcp:8811']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'code-server'
    static_configs:
      - targets: ['code-server-mama-bear:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
